#!/usr/bin/perl
use v5.24;
use warnings;

my ($n, $count);

while (<STDIN>) {
	chomp;
	next if /ab|cd|pq|xy/;
	next unless 3 <= ($n = () = $_ =~ /[aeiou]/g);
	next unless /(.)\1/;
	$count++;
}

say 'part 1: ', $count;
